#Plotting and data libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(ecodata)
library(here)
library(kableExtra)
library(ggrepel)
library(stringr)
library(patchwork)
library(grid)
library(vegan)
library(RColorBrewer)
library(rpart)
library(drake)

#GIS libraries
library(sf)
library(rgdal)
library(raster)
library(rnaturalearth)